name: Dota 2 Data Extraction

on:
  schedule:
    - cron: '0 0 1 * *'  # Essa tarefa será executada uma vez por mês, à meia-noite do dia 1 de cada mês.
  workflow_dispatch:  # Permite execução manual

jobs:
  extract-data:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install polars boto3 pyarrow requests pytz
        
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "AWS credentials configured"
        
    - name: Run data extraction
      
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_REGION=${{ secrets.AWS_REGION }}
        cd src/dota/full-load
        python extract-data-dota.py 
